{% set name = "pyo-oracle" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bio-oracle/pyo_oracle/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5f93d6677eabd3ed7af9a2d66a8a02177a165f321b29d8182a64e6119cbff237

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - erddapy

test:
  imports:
    - pyo_oracle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bio-oracle/pyo_oracle
  summary: Python API client for the Bio-ORACLE ERDDAP server.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - vinisalazar
